services:
  - type: web
    name: news-scraper-frontend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://beackkayq.onrender.com
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_NAME
        value: News Scraper
      - key: NEXT_PUBLIC_APP_VERSION
        value: 1.0.0
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=() 