import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "./components/theme-provider";
import { ThemeSwitcher } from "./components/theme-switcher";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-200`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="sticky top-0 z-50 w-full border-b border-gray-200 bg-white/80 backdrop-blur-md dark:bg-gray-900/80 dark:border-gray-800">
            <nav className="max-w-7xl mx-auto flex items-center justify-between p-4">
              <div className="flex items-center gap-4">
                <Link href="/" className="font-bold text-lg text-gray-800 hover:text-blue-600 transition-colors dark:text-gray-200 dark:hover:text-blue-400">
                  News Scraper
                </Link>
              </div>
              <div className="flex items-center gap-4">
                <Link href="/settings" className="text-sm font-medium text-gray-600 hover:text-blue-600 transition-colors bg-gray-100 hover:bg-gray-200 px-3 py-2 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700">
                  Settings
                </Link>
                <ThemeSwitcher />
              </div>
            </nav>
          </header>
          <main className="py-8 sm:py-12">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
